---

# Setup passwordless SSH to the target machine
# Copy ~/.ssh/id_dsa.pub directly from it's location on the host machine 
# so it's not accidentally committed to the Git repository

- name: Create SSH directories
  file: path={{ item }}/.ssh mode=0700 state=directory owner={{ ansible_ssh_user }} group=staff
  with_items:
    - /Users/{{ ansible_ssh_user }}
    # - /var/root

- name: one-shot ssh key setup (will nuke existing keys)
  copy: src=~/.ssh/id_dsa.pub dest={{ item }}/.ssh/authorized_keys mode=0600 force=yes backup=yes
  with_items:
    - /Users/{{ ansible_ssh_user }}
    # - /var/root

# - name: Fix .ssh permissions for root
#   command: chown -R root:wheel /var/root/.ssh
