---

- name: 'Finder: Set sidebar icon size to small'
  shell: defaults write {{ user_lib_prefs }}/.GlobalPreferences NSTableViewDefaultSizeMode -int 1

- name: "Finder: Show status bar"
  shell: defaults write {{ user_lib_prefs }}/com.apple.finder ShowStatusBar -bool true

- name: 'Finder: Enable Airdrop on all network interfaces'
  shell: defaults write {{ user_lib_prefs }}/com.apple.NetworkBrowser BrowseAllInterfaces -bool true

- name: 'Finder: Set Dock from template'
  template: src=com.apple.dock.j2 dest={{ user_lib_prefs }}/com.apple.dock.plist

- name: Repair permissions
  shell: "chown -R {{ username }}:staff {{ user_lib_prefs }}/"

- name: 'Restart Dock'
  command: killall {{ item }}
  ignore_errors: yes
  with_items: 
    - Dock
    - Finder

